# HERO.yaml

# Model Parameters
embedding_size: 64  # Dimension of user/item embeddings
feat_embed_dim: 64  # Dimension for projected modal features
n_mm_layers: 2     # Number of multimodal graph layers
n_ui_layers: 2     # Number of user-item graph layers
n_heads: 4         # Number of attention heads for transformers
knn_k: 10         # Number of neighbors for KNN graph construction



# Regularization & Dropout
dropout: 0.3      # Dropout rate
reg_weight: 1e-4  # L2 regularization weight
contrast_weight: 0.2  # Weight for contrastive loss
temperature: 0.2  # Temperature for softmax in contrastive learning

# Modality Fusion
mm_fusion_mode: 'concat'  # Options: gate, concat, sum
mm_image_weight: 0.5   # Weight for visual modality in fusion
