# Hyperparameter configuration for MMRecModel

embedding_size: 64
feat_embed_dim: 64

# Number of layers for multimodal and user-item interactions
n_layers: 2

# Dropout rates to prevent overfitting
dropout: [0.1, 0.3, 0.5]

# Regularization weights for different components
reg_weight: [1e-5, 1e-4, 1e-3]

# Coefficient for multimodal weight
mm_image_weight: 0.1

# Coefficient for collaborative filtering loss
lambda_coeff: 0.9

# Number of user-item interaction layers
n_ui_layers: 2

# Degree ratio for normalization
degree_ratio: 0.8

# Additional hyperparameters
knn_k: 10

n_mm_layers: 2
cl_weight: 0.1
mm_image_weight: 0.1
temperature: 0.07
ssl_weight: 0.1
n_heads: 8
num_clusters: 10

hyper_parameters: ["dropout", "reg_weight"]