# Hyperparameter configuration for MMRecModel

embedding_size: 16
feat_embed_dim: 16

# Number of layers for multimodal and user-item interactions
n_layers: 2

# Dropout rates to prevent overfitting
dropout: 0.5

# Regularization weights for different components
reg_weight: 0.01

# Coefficient for multimodal weight
mm_image_weight: 1.0

# Coefficient for collaborative filtering loss
lambda_coeff: 0.5

# Number of user-item interaction layers
n_ui_layers: 2

# Degree ratio for normalization
degree_ratio: 0.5

# Additional hyperparameters
knn_k: 10

n_mm_layers: 1
cl_weight: 2.0
mm_image_weight: 0.5