embedding_size: 32
feat_embed_dim: 32
n_layers: 1
dropout: 0.1
cl_weight: 1.0
reg_weight: 2e-04
knn_k: 10
lambda_coeff: 0.5
reward_gamma: 0.99
contextual_factor: 0.2
time_decay: 0.8

ssl_temp: 0.1 
ssl_reg: 0.1
knn_k: 10






