embedding_size: 64          # Dimension of embeddings
feat_embed_dim: 64         # Dimension of modality feature embeddings
num_layers: 2               # Number of GAT layers
num_heads: 4                # Number of attention heads in GAT
dropout_rate: 0.2           # Dropout rate
alpha: 0.2                  # LeakyReLU negative slope
reg_weight: 1e-5            # Regularization weight
ssl_weight: 0.1             # Weight for self-supervised loss
ssl_temp: 0.5               # Temperature for contrastive loss
ssl_dropout: 0.1            # Dropout for augmenting embeddings